name: GoReleaser
on:
 push:
   tags:
   - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: 1.13
    - name: Check out code
      uses: actions/checkout@v1
    - name: Login to dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release --rm-dist
