name: Test
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install dependency
      run: |
        go mod download

    - name: Lint Go Code
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        go get -u golang.org/x/lint/golint
        golint -min_confidence=0.3 -set_exit_status ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install dependency
      run: |
        go mod download

    - name: Run Unit tests.
      run: |
        go test -short -covermode=atomic ./...
